name: check & build & deploy

on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:

jobs:
  markdown-lint:
    name: Lint repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
      - name: Install mdl
        run: gem install mdl
      - name: Run markdown-linter
        run: mdl -s .github/workflows/markdown_linter_rules.rb docs/.

  markdown-link-check:
    name: Check links
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'no'
        use-verbose-mode: 'yes'
        config-file: '.github/workflows/markdown_link_check_config.json'

  build:
    runs-on: ubuntu-latest
    needs: [markdown-lint, markdown-link-check]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
      - run: mkdocs build --verbose
      - if: github.ref == 'refs/heads/main'
        run: mkdocs gh-deploy --force
